/* eslint-disable global-require */
const ImageLinks = {

  /* Category */
  caps: require('../assets/images/category/caps.jpg'),
  clock: require('../assets/images/category/clock.jpg'),
  coaster: require('../assets/images/category/coaster.jpg'),
  diary: require('../assets/images/category/diary.jpg'),
  mug: require('../assets/images/category/mug.jpg'),
  pen: require('../assets/images/category/pen.jpg'),
  photoframes: require('../assets/images/category/photoframes.jpg'),
  sippers: require('../assets/images/category/sippers.jpg'),
  tshirts: require('../assets/images/category/tshirt.jpg'),

  /* Banner */

  bannerShirt: require('../assets/images/banner/bannerShirt.jpg'),
  corporateGift: require('../assets/images/banner/corporateGitft.jpg'),
  customBrand: require('../assets/images/banner/customBrand.jpg'),

  /* Logo */

  logo: require('../assets/images/logo.png'),
  blackLogo: require('../assets/images/blackLogo.png'),

  apparel: require('../assets/images/section/cateroryBanner/apparel.webp'),
  business: require('../assets/images/section/cateroryBanner/business.webp'),
  corporate: require('../assets/images/section/cateroryBanner/corporate.webp'),
  label: require('../assets/images/section/cateroryBanner/lable.webp'),
  marketing: require('../assets/images/section/cateroryBanner/marketing.webp'),
  photo: require('../assets/images/section/cateroryBanner/photoGifts.webp'),
  stationary: require('../assets/images/section/cateroryBanner/stationary.webp'),
  sticker: require('../assets/images/section/cateroryBanner/sticker.webp'),
  cafe: require('../assets/images/section/Square banner/cafe.webp'),
  employee: require('../assets/images/section/Square banner/employee.webp'),
  event: require('../assets/images/section/Square banner/event.webp'),
  startup: require('../assets/images/section/Square banner/startups.webp'),

  // Coaster
  birthday1: require('../assets/images/category/coaster/bIrthdayCoaster/brithday1.jpg'),
  birthday2: require('../assets/images/category/coaster/bIrthdayCoaster/birthday2.webp'),
  birthday3: require('../assets/images/category/coaster/bIrthdayCoaster/birthday3.jpg'),
  coasterPrint1: require('../assets/images/category/coaster/coasterPrint/printed1.jpg'),
  coasterPrint2: require('../assets/images/category/coaster/coasterPrint/printed2.jpg'),
  coasterPrint3: require('../assets/images/category/coaster/coasterPrint/printed3.jpg'),
  designerCoaster1: require('../assets/images/category/coaster/designerCoaster/designer1.jpg'),
  designerCoaster2: require('../assets/images/category/coaster/designerCoaster/designer2.jpg'),
  designerCoaster3: require('../assets/images/category/coaster/designerCoaster/designer3.jpg'),
  normalCoaster1: require('../assets/images/category/coaster/normalCoaster/normal1.jpg'),
  normalCoaster2: require('../assets/images/category/coaster/normalCoaster/normal2.jpg'),
  normalCoaster3: require('../assets/images/category/coaster/normalCoaster/normal3.jpg'),
  normalCoaster4: require('../assets/images/category/coaster/normalCoaster/normal4.jpg'),
  printCoaster1: require('../assets/images/category/coaster/printCoaster/print1.jpg'),
  printCoaser2: require('../assets/images/category/coaster/printCoaster/print2.jpg'),
  redCoaster1: require('../assets/images/category/coaster/redCoaster/red1.jpg'),
  redCoaster2: require('../assets/images/category/coaster/redCoaster/red2.jpg'),
  redCoaster3: require('../assets/images/category/coaster/redCoaster/red3.webp'),
  redCoaster4: require('../assets/images/category/coaster/redCoaster/red4.jpg'),
  woodenCoaster1: require('../assets/images/category/coaster/woodenCoaster/wooden1.jpg'),
  woodenCoaster2: require('../assets/images/category/coaster/woodenCoaster/wooden2.jpg'),
  woodenCoaster3: require('../assets/images/category/coaster/woodenCoaster/wooden3.jpg'),
  yellowCoaster1: require('../assets/images/category/coaster/yellowCoaster/yellow1.jpg'),
  yellowCoaster2: require('../assets/images/category/coaster/yellowCoaster/yellow2.jpg'),
  yellowCoaster3: require('../assets/images/category/coaster/yellowCoaster/yellow3.jpg'),

  // Mugs
  chariot: require('../assets/images/category/mugs/chariot.jpg'),
  couch: require('../assets/images/category/mugs/couch.jpg'),
  eye: require('../assets/images/category/mugs/eye.jpg'),
  lastStraw: require('../assets/images/category/mugs/lastStraw.jpg'),
  lover: require('../assets/images/category/mugs/lover.jpg'),
  mom: require('../assets/images/category/mugs/mom.jpg'),
  plain: require('../assets/images/category/mugs/plain.jpg'),
  pricks: require('../assets/images/category/mugs/pricks.jpg'),
  relaxation: require('../assets/images/category/mugs/relaxation.jpg'),
  show: require('../assets/images/category/mugs/show.jpg'),
  star: require('../assets/images/category/mugs/star.jpg'),
  starMug: require('../assets/images/category/mugs/starMug.jpg'),
  strength: require('../assets/images/category/mugs/stength.jpg'),
  symbol: require('../assets/images/category/mugs/symbol.jpg'),
  tarrot1: require('../assets/images/category/mugs/tarrot1.jpg'),
  tarrot2: require('../assets/images/category/mugs/terrot2.jpg'),
  tarrot3: require('../assets/images/category/mugs/terrot3.jpg'),
  tarrot4: require('../assets/images/category/mugs/terrot4.jpg'),
  tarrot5: require('../assets/images/category/mugs/terrot5.jpg'),
  yoga: require('../assets/images/category/mugs/yoga.jpg'),


  // Sipper

  blackSipper: require('../assets/images/category/sipper/blackBottle2.jpg'),
  blackSipper2: require('../assets/images/category/sipper/blackBottle3 .jpg'),
  sipperBlack: require('../assets/images/category/sipper/sipperBlack.jpg'),
  sipperBlue: require('../assets/images/category/sipper/sipperBlue.jpg'),
  sipperRed: require('../assets/images/category/sipper/sipperRed.jpg'),
  sipperRed2: require('../assets/images/category/sipper/sipperRed2.jpg'),
  sipperSilver: require('../assets/images/category/sipper/SipperSilver.jpg'),
  sipperSilver2: require('../assets/images/category/sipper/sipperSilver2 .jpg'),
  sipperWhite: require('../assets/images/category/sipper/sipperWhite.jpg'),

  // Tshirts

  darkGreen: require('../assets/images/category/tShirt/darkGreen/darkGreen1.jpg'),
  green: require('../assets/images/category/tShirt/green/green1.jpg'),
  lavender: require('../assets/images/category/tShirt/lavender/lavender1.jpg'),
  lightGreen: require('../assets/images/category/tShirt/lightGarden/lightGarden1.jpg'),
  mintGreen: require('../assets/images/category/tShirt/mintGreen/mintGreen1.jpg'),
  skyBlueTshirt: require('../assets/images/category/tShirt/skyBlue/skyBlue1.jpg'),
  white: require('../assets/images/category/tShirt/white/white1.jpg'),
  achieveYourLifeStream: require("../assets/images/category/tShirt/black/achieveYourLifeStream.jpg"),
  AlwaysPositive: require("../assets/images/category/tShirt/black/Always positive.jpg"),
  AumOmOhm: require("../assets/images/category/tShirt/black/AumOmOhm.jpg"),
  BaddestWitchAround: require("../assets/images/category/tShirt/black/BaddestWitchAround.jpg"),
  Chokurei: require("../assets/images/category/tShirt/black/Chokurei.jpg"),
  CreativityIsNotCompetition: require("../assets/images/category/tShirt/black/Creativity is not competition copy.jpg"),
  CreativityIsIntelligenceHavingFun: require("../assets/images/category/tShirt/black/CreativityIsIntelligenceHavingFun.jpg"),
  Daikomyo: require("../assets/images/category/tShirt/black/Daikomyo.jpg"),
  Daikomyo2: require("../assets/images/category/tShirt/black/Daikomyo2.jpg"),
  Daikomyo3: require("../assets/images/category/tShirt/black/daikomyo3.jpg"),
  DoMoreOfWhatMakesYouHappy: require("../assets/images/category/tShirt/black/Domoreofwhatmakeyouhappy.jpg"),
  FireSerpent: require("../assets/images/category/tShirt/black/fireSerpent.jpg"),
  Gnosa: require("../assets/images/category/tShirt/black/gnosa.jpg"),
  Hand: require("../assets/images/category/tShirt/black/hand.jpg"),
  Hand2: require("../assets/images/category/tShirt/black/hand2.jpg"),
  Harth: require("../assets/images/category/tShirt/black/harth.jpg"),
  HealingEnergyNeverFades: require("../assets/images/category/tShirt/black/healingEnergyNeverFades.jpg"),
  HonShaZeShoNen: require("../assets/images/category/tShirt/black/HonShaZeShoNen.jpg"),
  LifeIsShortAndTheWorldIsWide: require("../assets/images/category/tShirt/black/Lifeisshortandtheworldiswide.jpg"),
  MeditationIsAPowerfulResource: require("../assets/images/category/tShirt/black/meditationisapowerfulrecource.jpg"),
  Namaste: require("../assets/images/category/tShirt/black/namaste.jpg"),
  NotAllHeroesWear: require("../assets/images/category/tShirt/black/notallheroeswear.jpg"),
  PalmDaikomyo: require("../assets/images/category/tShirt/black/palmdikomio.jpg"),
  Palmistry: require("../assets/images/category/tShirt/black/palmistry.jpg"),
  Reiki: require("../assets/images/category/tShirt/black/reiki.jpg"),
  ReikiMaster: require("../assets/images/category/tShirt/black/reikiMaster.jpg"),
  ReikiModeOn: require("../assets/images/category/tShirt/black/reikiModeOn.jpg"),
  SendingYouHealingEnergy: require("../assets/images/category/tShirt/black/sendingyouhealingenergy.jpg"),
  SevenChakras: require("../assets/images/category/tShirt/black/sevenchakras.jpg"),
  ShineYourHealingLight: require("../assets/images/category/tShirt/black/shineyourhealinglight.jpg"),
  TakeYourDreamsSeriously: require("../assets/images/category/tShirt/black/takeyourdreamsseriously.jpg"),
  TheArtOfPalmistry: require("../assets/images/category/tShirt/black/theartofpalmistry.jpg"),
  TheBestWayToPredictFuture: require("../assets/images/category/tShirt/black/thebestwaytopredictfuture.jpg"),
  TrustYourCrazyIdeas: require("../assets/images/category/tShirt/black/trustyourcrazyideas.jpg"),
  YourDesignHere: require("../assets/images/category/tShirt/black/Yourdesignhere.jpg"),
  Zona: require("../assets/images/category/tShirt/black/zona.jpg"),


  // Diary and Planners

  black: require('../assets/images/category/planner/black-PPN-29.jpg'),
  brightOrange: require('../assets/images/category/planner/brightOrange-PPN-19.jpg'),
  darkBlue: require('../assets/images/category/planner/darkBlue-PPN-04.jpg'),
  darkGray: require('../assets/images/category/planner/darkGray-PPN-05.jpg'),
  darkOrange: require('../assets/images/category/planner/darkOrange-PPN-06.jpg'),
  deepDarkBlue: require('../assets/images/category/planner/deepDarkBlue-PPN-13.jpg'),
  deepSkyBlue: require('../assets/images/category/planner/deepSkyBlue-PPN-30.jpg'),
  deepOrange: require('../assets/images/category/planner/dualOrange-PPN-16.jpg'),
  elegantGray: require('../assets/images/category/planner/elegantGray-PPN-31.jpg'),
  fabricatedSkyBlue: require('../assets/images/category/planner/fabricatedSkyBlue-PPN-15.jpg'),
  fadedBrown: require('../assets/images/category/planner/fadedBrown-PPN-20.jpg'),
  grayDiary: require('../assets/images/category/planner/grayDiary-PPN-01.jpg'),
  lightBrown: require('../assets/images/category/planner/lightBrown-PPN-14.jpg'),
  lightRoyalGreen: require('../assets/images/category/planner/lightGrayRoyal-PPN-23.jpg'),
  lightSkyBlue: require('../assets/images/category/planner/ligthSkyBlue-PPN-10.jpg'),
  linedDarkBlue: require('../assets/images/category/planner/linedDarkBlue-PPN-08.jpg'),
  linedLightBlue: require('../assets/images/category/planner/linedLightBlue-PPN-07.jpg'),
  maroon: require('../assets/images/category/planner/maroon-PPN-11.jpg'),
  orange: require('../assets/images/category/planner/orange-PPN-03.jpg'),
  royalBlue: require('../assets/images/category/planner/royalBlue-PPN-22.jpg'),
  royalDarkGray: require('../assets/images/category/planner/royalDarkGrayPPN-24.jpg'),
  shaded: require('../assets/images/category/planner/shaded-PPN-12.jpg'),
  skyBlue: require('../assets/images/category/planner/skyBlue-PPN-02.jpg'),
  woodenBrown: require('../assets/images/category/planner/woodenBrown-PPN-25.jpg'),

  // Bags

  blueJute: require('../assets/images/category/bags/blueJuteBag.jpg'),
  brownJute: require('../assets/images/category/bags/brownJuteBag.jpg'),
  darkBrownJute: require('../assets/images/category/bags/brownJuteBag2.jpg'),
  colorFulJute: require('../assets/images/category/bags/colorfulJuteBag.jpg'),
  juteBagWithHanging: require('../assets/images/category/bags/juteBagWithHanging.jpg'),
  orangeBag: require('../assets/images/category/bags/orangeBag.jpg'),
  redBag: require('../assets/images/category/bags/redBag.jpg'),
  whiteWindowBag: require('../assets/images/category/bags/whiteWindowBag.jpg'),
  windowJuteBag: require('../assets/images/category/bags/windowJuteBag.jpg'),

  // Pens

  pen1: require('../assets/images/category/pen/wrapTee24001.jpg'),
  pen2: require('../assets/images/category/pen/wrapTee24002.jpg'),
  pen3: require('../assets/images/category/pen/wrapTee24003.jpg'),
  pen4: require('../assets/images/category/pen/wrapTee24004.jpg'),
  pen5: require('../assets/images/category/pen/wrapTee24005.jpg'),
  pen6: require('../assets/images/category/pen/wrapTee24006.jpg'),
  pen7: require('../assets/images/category/pen/wrapTee24007.jpg'),
  pen8: require('../assets/images/category/pen/wrapTee24008.jpg'),
  pen9: require('../assets/images/category/pen/wrapTee24009.jpg'),
  pen10: require('../assets/images/category/pen/wrapTee24010.jpg'),
  pen11: require('../assets/images/category/pen/wrapTee24011.jpg'),
  pen12: require('../assets/images/category/pen/wrapTee24012.jpg'),
  pen13: require('../assets/images/category/pen/wrapTee24013.jpg'),
  pen14: require('../assets/images/category/pen/wrapTee24014.jpg'),
  pen15: require('../assets/images/category/pen/wrapTee24015.jpg'),
  pen16: require('../assets/images/category/pen/wrapTee24016.jpg'),
  pen17: require('../assets/images/category/pen/wrapTee24017.jpg'),
  pen18: require('../assets/images/category/pen/wrapTee24018.jpg'),
  pen19: require('../assets/images/category/pen/wrapTee24019.jpg'),
  pen20: require('../assets/images/category/pen/wrapTee24020.jpg'),
  pen21: require('../assets/images/category/pen/wrapTee24021.jpg'),
  pen22: require('../assets/images/category/pen/wrapTee24022.jpg'),
  pen23: require('../assets/images/category/pen/wrapTee24023.jpg'),
  pen24: require('../assets/images/category/pen/wrapTee24024.jpg'),
  pen25: require('../assets/images/category/pen/wrapTee24025.jpg'),
  pen26: require('../assets/images/category/pen/wrapTee24026.jpg'),
  pen27: require('../assets/images/category/pen/wrapTee24027.jpg'),
  pen28: require('../assets/images/category/pen/wrapTee24028.jpg'),
  pen29: require('../assets/images/category/pen/wrapTee24029.jpg'),
  pen30: require('../assets/images/category/pen/wrapTee24030.jpg'),
  pen31: require('../assets/images/category/pen/wrapTee24031.jpg'),
  pen32: require('../assets/images/category/pen/wrapTee24032.jpg'),
  pen33: require('../assets/images/category/pen/wrapTee24033.jpg'),
  pen34: require('../assets/images/category/pen/wrapTee24034.jpg'),
  pen35: require('../assets/images/category/pen/wrapTee24035.jpg'),

  // Gift Sets

  gift1: require('../assets/images/category/giftSet/giftSet1.jpg'),
  gift2: require('../assets/images/category/giftSet/giftSet2.jpg'),
  gift3: require('../assets/images/category/giftSet/giftSet3.jpg'),
  gift4: require('../assets/images/category/giftSet/giftSet4.jpg'),
  gift5: require('../assets/images/category/giftSet/giftSet5.jpg'),
  gift6: require('../assets/images/category/giftSet/giftSet6.jpg'),
  gift7: require('../assets/images/category/giftSet/giftSet7.jpg'),
  gift8: require('../assets/images/category/giftSet/giftSet8.jpg'),
  gift9: require('../assets/images/category/giftSet/giftSet9.jpg'),
  gift10: require('../assets/images/category/giftSet/giftSet10.jpg'),
  gift11: require('../assets/images/category/giftSet/giftSet11.jpg'),
  gift12: require('../assets/images/category/giftSet/giftSet12.jpg'),
  gift13: require('../assets/images/category/giftSet/giftSet13.jpg'),
  gift14: require('../assets/images/category/giftSet/giftSet14.jpg'),
  gift15: require('../assets/images/category/giftSet/giftSet15.jpg'),
  gift16: require('../assets/images/category/giftSet/giftSet16.jpg'),
  gift17: require('../assets/images/category/giftSet/giftSet17.jpg'),
  gift18: require('../assets/images/category/giftSet/giftSet18.jpg'),
  gift19: require('../assets/images/category/giftSet/giftSet19.jpg'),
  gift20: require('../assets/images/category/giftSet/giftSet20.jpg'),
  gift21: require('../assets/images/category/giftSet/giftSet21.jpg'),
  gift22: require('../assets/images/category/giftSet/giftSet22.jpg'),
  gift23: require('../assets/images/category/giftSet/giftSet23.jpg'),
  gift24: require('../assets/images/category/giftSet/giftSet24.jpg'),
  gift25: require('../assets/images/category/giftSet/giftSet25.jpg'),
  gift26: require('../assets/images/category/giftSet/giftSet26.jpg'),
  gift27: require('../assets/images/category/giftSet/giftSet27.jpg'),
  gift28: require('../assets/images/category/giftSet/giftSet28.jpg'),
  gift29: require('../assets/images/category/giftSet/giftSet29.jpg'),
  gift30: require('../assets/images/category/giftSet/giftSet30.jpg'),
  gift31: require('../assets/images/category/giftSet/giftSet31.jpg'),
  gift32: require('../assets/images/category/giftSet/giftSet32.jpg'),
  gift33: require('../assets/images/category/giftSet/giftSet33.jpg'),
  gift34: require('../assets/images/category/giftSet/giftSet34.jpg'),
  gift35: require('../assets/images/category/giftSet/giftSet35.jpg'),
  gift36: require('../assets/images/category/giftSet/giftSet36.jpg'),
  gift37: require('../assets/images/category/giftSet/giftSet37.jpg'),
  gift38: require('../assets/images/category/giftSet/giftSet38.jpg'),
  gift39: require('../assets/images/category/giftSet/giftSet39.jpg'),
  gift40: require('../assets/images/category/giftSet/giftSet40.jpg'),
  gift41: require('../assets/images/category/giftSet/giftSet41.jpg'),
  gift42: require('../assets/images/category/giftSet/giftSet42.jpg'),
  gift43: require('../assets/images/category/giftSet/giftSet43.jpg'),
  gift44: require('../assets/images/category/giftSet/giftSet44.jpg'),
  gift45: require('../assets/images/category/giftSet/giftSet45.jpg'),

};
export default ImageLinks;
