import ImageLinks from "./imageLink";

const productData = [
  // Coasters
  {
    sku: "cst001",
    name: "Festive Birthday Celebration Coaster (6pcs)",
    price: 499,
    category: "coaster",
    imageUrl: ImageLinks.birthday1,
    description: "Celebrate every sip with our vibrant Birthday Coaster, designed to add a festive touch to your table. Perfect for all your special occasions and durable enough for everyday use.",
  },
  {
    sku: "cst002",
    name: "Ethenic Printed Coaster (6pcs)",
    price: 499,
    category: "coaster",
    imageUrl: ImageLinks.coasterPrint1,
    description: "Add a touch of sophistication to your tableware with our Elegant Printed Coaster, featuring a stylish square design and premium quality to protect your surfaces in style.",
  },
  {
    sku: "cst003",
    name: "Artisan Designer Wooden Coaster (6pcs)",
    price: 499,
    category: "coaster",
    imageUrl: ImageLinks.designerCoaster1,
    description: "Elevate your home décor with our Designer Coaster, crafted from high-quality wood and boasting intricate designs that blend functionality with artistry.",
  },
  {
    sku: "cst004",
    name: "Minimalistic Rich-Design Coaster (6pcs)",
    price: 499,
    category: "coaster",
    imageUrl: ImageLinks.normalCoaster1,
    description: "Keep it classy and practical with our Simple Rich Coaster. Its minimalistic design and robust material make it a versatile addition to any home or office setup.",
  },
  {
    sku: "cst005",
    name: "Personalized Printed Coaster for Every Occasion (6pcs)",
    price: 499,
    category: "coaster",
    imageUrl: ImageLinks.printCoaster1,
    description: "Create a personalized statement with our Customize Printed Coaster. Add your unique designs or messages to make every coffee break memorable.",
  },
  {
    sku: "cst006",
    name: "Rustic Elegant Wooden Coaster (6pc)",
    price: 499,
    category: "coaster",
    imageUrl: ImageLinks.woodenCoaster1,
    description: "Experience timeless elegance with our Elegant Wooden Coaster. Handcrafted from premium wood, it brings a natural, rustic charm to your table.",
  },
  {
    sku: "cst007",
    name: "Bright and Cheerful Yellow Shade Coaster (6pcs)",
    price: 499,
    category: "coaster",
    imageUrl: ImageLinks.yellowCoaster1,
    description: "Brighten up your dining experience with our Elegant Yellow Shade Coaster. Its cheerful color and sturdy design make it the perfect companion for your beverages.",
  },


  // Mugs
  {
    sku: "cup001",
    name: "Vintage Charm Chariot Mug",
    price: 599,
    category: "cup",
    imageUrl: ImageLinks.chariot,
    description: "Sip in style with the Elegant Chariot Mug, featuring a sophisticated design inspired by vintage chariots. Perfect for your favorite hot beverages and a delightful addition to your mug collection.",
  },
  {
    sku: "cup002",
    name: "Cozy Comfort Couch Mug",
    price: 599,
    category: "cup",
    imageUrl: ImageLinks.couch,
    description: "Relax and unwind with the Elegant Couch Mug. Its cozy design makes every sip feel like a comforting moment on your favorite couch.",
  },
  {
    sku: "cup003",
    name: "Captivating Eye Look Mug",
    price: 599,
    category: "cup",
    imageUrl: ImageLinks.eye,
    description: "Start your mornings with a captivating gaze! The Eye Look Mug brings charm and mystery to your coffee rituals, making every sip unforgettable.",
  },
  {
    sku: "cup004",
    name: "Modern Flair Last Straw Mug",
    price: 599,
    category: "cup",
    imageUrl: ImageLinks.lastStraw,
    description: "The Elegant Last Straw Mug is your go-to for a bold statement. With its modern design and vibrant aesthetics, it’s perfect for those who love standing out.",
  },
  {
    sku: "cup005",
    name: "Romantic Elegance Lover Mug",
    price: 599,
    category: "cup",
    imageUrl: ImageLinks.lover,
    description: "Celebrate love with the Elegant Lover Mug. A perfect gift for your special someone, this mug embodies romance and warmth in every sip.",
  },
  {
    sku: "cup006",
    name: "Heartwarming Mom Custom Mug",
    price: 599,
    category: "cup",
    imageUrl: ImageLinks.mom,
    description: "Show your love for Mom with a personal touch! The Elegant Customize Mom Mug allows you to add your unique design or message for a heartwarming gift.",
  },
  {
    sku: "cup007",
    name: "Timeless Simplicity Plain Mug",
    price: 599,
    category: "cup",
    imageUrl: ImageLinks.plain,
    description: "Simplicity meets elegance with the Elegant Plain Mug. Its timeless design is perfect for any beverage, blending seamlessly into any kitchen aesthetic.",
  },
  {
    sku: "cup008",
    name: "Playful Quirks Prick Mug",
    price: 599,
    category: "cup",
    imageUrl: ImageLinks.pricks,
    description: "Add a playful touch to your mornings with the Elegant Prick Mug. Featuring quirky designs, it’s a fun way to start your day.",
  },
  {
    sku: "cup0010",
    name: "Calm Serenity Relaxed Mug",
    price: 599,
    category: "cup",
    imageUrl: ImageLinks.relaxation,
    description: "Take a break and enjoy serenity with the Elegant Relaxed Mug. Its calming design and ergonomic shape are perfect for unwinding with your favorite drink.",
  },
  {
    sku: "cup0011",
    name: "Bold Style Show Mug",
    price: 599,
    category: "cup",
    imageUrl: ImageLinks.show,
    description: "Be the star of every coffee break with the Elegant Show Mug. Featuring a bold and eye-catching design, it’s the perfect conversation starter.",
  },
  {
    sku: "cup0012",
    name: "Shimmering Star Mug",
    price: 599,
    category: "cup",
    imageUrl: ImageLinks.star,
    description: "Shine bright every morning with the Elegant Star Mug. Its stellar design and durable build make it a must-have for every stargazer.",
  },
  {
    sku: "cup0013",
    name: "Personalized Starry Mug",
    price: 599,
    category: "cup",
    imageUrl: ImageLinks.starMug,
    description: "Make it yours with the Customize Star Mug! Personalize it with your favorite starry design for a truly unique coffee experience.",
  },
  {
    sku: "cup0014",
    name: "Empowering Strength Mug",
    price: 599,
    category: "cup",
    imageUrl: ImageLinks.strength,
    description: "Embrace your inner strength with the Elegant Strength Mug. Its bold design inspires confidence and determination with every sip.",
  },
  {
    sku: "cup0015",
    name: "Statement Symbol Mug",
    price: 599,
    category: "cup",
    imageUrl: ImageLinks.symbol,
    description: "Make a statement with the Elegant Symbol Mug. Its unique design symbolizes style and individuality, perfect for your daily caffeine fix.",
  },
  {
    sku: "cup0016",
    name: "Mystic Universe Tarot Mug",
    price: 599,
    category: "cup",
    imageUrl: ImageLinks.tarrot1,
    description: "Discover the mysteries of the universe with the Elegant Tarot Mug. Perfect for tea, coffee, or a bit of morning fortune-telling.",
  },
  {
    sku: "cup0017",
    name: "Customizable Tarot Mug",
    price: 599,
    category: "cup",
    imageUrl: ImageLinks.tarrot2,
    description: "Add a personal twist to your Tarot readings with the Elegant Customize Tarot Mug. Make it uniquely yours with custom designs.",
  },
  {
    sku: "cup0018",
    name: "Artistic Design Tarot Mug",
    price: 599,
    category: "cup",
    imageUrl: ImageLinks.tarrot3,
    description: "Infuse your mornings with intrigue and elegance with the Designed Tarot Mug. Its intricate patterns bring a touch of magic to every sip.",
  },
  {
    sku: "cup0019",
    name: "Mystical Tarot Printed Mug",
    price: 599,
    category: "cup",
    imageUrl: ImageLinks.tarrot4,
    description: "Start your day with a mystical vibe! The Elegant Tarot Printed Mug features stunning designs inspired by Tarot, perfect for the spiritually inclined.",
  },
  {
    sku: "cup0020",
    name: "Custom Mystical Tarot Mug",
    price: 599,
    category: "cup",
    imageUrl: ImageLinks.tarrot5,
    description: "Bring your personal style to the table with the Elegant Tarot Customize Mug. Perfect for custom designs with a mystical flair.",
  },
  {
    sku: "cup0021",
    name: "Mindful Yoga Custom Mug",
    price: 599,
    category: "cup",
    imageUrl: ImageLinks.yoga,
    description: "Embrace tranquility with the Elegant Customize Yoga Mug. Personalize it to reflect your yoga journey and enjoy a mindful moment with every sip.",
  },


  // Sipper
  {
    sku: "sipper001",
    name: "Sleek Personalized Black Sipper",
    price: 399,
    category: "sipper",
    imageUrl: ImageLinks.blackSipper,
    description: "Stay refreshed in style with the Customize Black Sipper. Its sleek black design and customizable surface make it perfect for personalizing with your name or logo. Durable, lightweight, and ideal for daily hydration on the go.",
  },
  {
    sku: "sipper002",
    name: "Modern Elegance Round Black Sipper",
    price: 399,
    category: "sipper",
    imageUrl: ImageLinks.blackSipper2,
    description: "The Elegant Round Black Sipper combines premium craftsmanship with a modern design. Perfect for gym-goers, office use, or outdoor adventures, this sipper keeps your beverages fresh and your style on point.",
  },
  {
    sku: "sipper003",
    name: "Bold Black Hydration Companion Sipper",
    price: 399,
    category: "sipper",
    imageUrl: ImageLinks.sipperBlack,
    description: "Upgrade your hydration game with the Elegant Black Sipper. Its bold black finish and ergonomic design ensure a comfortable grip, while its sturdy build keeps you hydrated in any environment.",
  },
  {
    sku: "sipper004",
    name: "Vibrant Custom Blue Sipper",
    price: 399,
    category: "sipper",
    imageUrl: ImageLinks.sipperBlue,
    description: "Brighten your day with the Customize Blue Sipper. Its vibrant blue color and personalization options make it a standout accessory for work, workouts, or leisure. Built to last and designed for convenience.",
  },
  {
    sku: "sipper005",
    name: "Striking Red Personalized Sipper",
    price: 399,
    category: "sipper",
    imageUrl: ImageLinks.sipperRed,
    description: "Add a bold touch to your daily routine with the Customize Red Sipper. Featuring a striking red hue and customizable design, it’s perfect for showcasing your unique style while staying hydrated.",
  },
  {
    sku: "sipper006",
    name: "Sleek Silver Elegance Sipper",
    price: 399,
    category: "sipper",
    imageUrl: ImageLinks.sipperSilver,
    description: "Elegance meets functionality in the Customize Silver Sipper. Its sleek metallic finish, lightweight design, and personalization options make it a must-have for professionals and fitness enthusiasts alike.",
  },
  {
    sku: "sipper007",
    name: "Minimalist White Personalized Sipper",
    price: 399,
    category: "sipper",
    imageUrl: ImageLinks.sipperWhite,
    description: "Keep it classic with the Customize White Sipper. Perfect for minimalists, its clean white finish pairs beautifully with custom prints, making it a versatile and stylish choice for all occasions.",
  },

  // Tshirts

  {
    sku: "tshirt001",
    name: "Classic White Customizable T-shirt",
    price: 399,
    category: "tshirt",
    imageUrl: ImageLinks.white,
    description: "Create your own style with the Customize White T-shirt. This classic white tee offers a clean canvas for personal designs, logos, or messages. Made with premium, breathable fabric for all-day comfort, it's perfect for casual outings or custom branding.",
  },
  {
    sku: "tshirt002",
    name: "Rich Dark Green Personalized T-shirt",
    price: 399,
    category: "tshirt",
    imageUrl: ImageLinks.darkGreen,
    description: "Stand out in the rich and earthy tones of the Customize Dark Green T-shirt. Ideal for personalization, this shirt combines a bold color with durable, soft material, making it a go-to choice for events, promotions, or everyday wear.",
  },
  {
    sku: "tshirt003",
    name: "Vibrant Green Customizable T-shirt",
    price: 399,
    category: "tshirt",
    imageUrl: ImageLinks.green,
    description: "Brighten your wardrobe with the Customize Green T-shirt. Its vibrant shade and customizable surface make it perfect for expressing your personality or promoting your brand. Lightweight and comfortable, it's designed for all-day versatility.",
  },
  {
    sku: "tshirt004",
    name: "Elegant Lavender Customizable T-shirt",
    price: 399,
    category: "tshirt",
    imageUrl: ImageLinks.lavender,
    description: "Embrace elegance with the Customize Lavender T-shirt. This soft, pastel-colored tee offers a subtle yet stylish look. Customize it with unique designs to create a standout piece for any casual or professional setting.",
  },
  {
    sku: "tshirt005",
    name: "Soothing Light Green Custom T-shirt",
    price: 399,
    category: "tshirt",
    imageUrl: ImageLinks.lightGreen,
    description: "Refresh your wardrobe with the Customize Light Green T-shirt. Its gentle, soothing shade pairs effortlessly with custom prints or logos, making it an ideal choice for casual days, team events, or brand promotion.",
  },
  {
    sku: "tshirt006",
    name: "Trendy Mint Green Customizable Tee",
    price: 399,
    category: "tshirt",
    imageUrl: ImageLinks.mintGreen,
    description: "Stay cool and stylish with the Customize Mint T-shirt. This refreshing color brings a modern twist to a classic tee. Add personalized designs to make it uniquely yours while enjoying its soft, breathable fabric.",
  },
  {
    sku: "tshirt007",
    name: "Sky Blue Custom T-shirt for All Occasions",
    price: 399,
    category: "tshirt",
    imageUrl: ImageLinks.skyBlue,
    description: "Elevate your look with the Customize Sky Blue T-shirt. Its calming blue shade and customization options allow you to showcase your creativity. Perfect for casual wear, team uniforms, or promotional events.",
  },  

  // Photo Frames
  {
    sku: "dpl001",
    name: "Elegant Leather Planner",
    price: 19,
    category: "diaries or planner",
    imageUrl: ImageLinks.cafe,
    description: "Organize your life with the Elegant Leather Planner. Featuring premium leather covers and smooth pages, it’s perfect for daily schedules, goal setting, and creative journaling.",
  },
  {
    sku: "dpl002",
    name: "Classic Hardcover Diary",
    price: 19,
    category: "diaries or planner",
    imageUrl: ImageLinks.cafe,
    description: "Capture your thoughts and ideas with the Classic Hardcover Diary. Its durable binding and high-quality paper make it an ideal companion for journaling, note-taking, or sketching.",
  },
  {
    sku: "dpl003",
    name: "Portable Pocket Planner",
    price: 19,
    category: "diaries or planner",
    imageUrl: ImageLinks.cafe,
    description: "Stay on top of your schedule wherever you go with the Portable Pocket Planner. Its compact size fits perfectly in your bag, ensuring productivity on the move.",
  },
  {
    sku: "dpl004",
    name: "Personalized Custom Planner",
    price: 29,
    category: "diaries or planner",
    imageUrl: ImageLinks.cafe,
    description: "Design your own planner with the Personalized Custom Planner. Tailor it with your favorite colors, layouts, or designs to suit your unique style and organizational needs.",
  },
  // Diaries or Planners
  {
    sku: "org001",
    name: "Stylish Desk Organizer",
    price: 19,
    category: "organiser",
    imageUrl: ImageLinks.cafe,
    description: "Keep your workspace tidy with the Stylish Desk Organizer. Featuring multiple compartments, it’s perfect for holding pens, stationery, and gadgets, adding efficiency to your desk setup.",
  },
  {
    sku: "org002",
    name: "Adjustable Drawer Organizer",
    price: 19,
    category: "organiser",
    imageUrl: ImageLinks.cafe,
    description: "Transform your drawers with the Adjustable Drawer Organizer. Its modular design helps you neatly arrange cutlery, tools, or office supplies, bringing order to every drawer.",
  },
  {
    sku: "org003",
    name: "Compact Travel Organizer",
    price: 19,
    category: "organiser",
    imageUrl: ImageLinks.cafe,
    description: "Simplify your journeys with the Compact Travel Organizer. Designed to store essentials like cables, chargers, and toiletries, it’s the ultimate travel companion for staying organized on the go.",
  },
  {
    sku: "org004",
    name: "Customizable Multi-Use Organizer",
    price: 29,
    category: "organiser",
    imageUrl: ImageLinks.cafe,
    description: "Personalize your storage with the Customizable Multi-Use Organizer. Perfect for home or office, its versatile design and customizable compartments cater to your unique organizational needs.",
  },

  // Organizers
  {
    sku: "dpl001",
    name: "Elegant Leather Planner",
    price: 19,
    category: "diaries or planner",
    imageUrl: ImageLinks.cafe,
    description: "Organize your life with the Elegant Leather Planner. Featuring premium leather covers and smooth pages, it’s perfect for daily schedules, goal setting, and creative journaling.",
  },
  {
    sku: "dpl002",
    name: "Classic Hardcover Diary",
    price: 19,
    category: "diaries or planner",
    imageUrl: ImageLinks.cafe,
    description: "Capture your thoughts and ideas with the Classic Hardcover Diary. Its durable binding and high-quality paper make it an ideal companion for journaling, note-taking, or sketching.",
  },
  {
    sku: "dpl003",
    name: "Portable Pocket Planner",
    price: 19,
    category: "diaries or planner",
    imageUrl: ImageLinks.cafe,
    description: "Stay on top of your schedule wherever you go with the Portable Pocket Planner. Its compact size fits perfectly in your bag, ensuring productivity on the move.",
  },
  {
    sku: "dpl004",
    name: "Personalized Custom Planner",
    price: 29,
    category: "diaries or planner",
    imageUrl: ImageLinks.cafe,
    description: "Design your own planner with the Personalized Custom Planner. Tailor it with your favorite colors, layouts, or designs to suit your unique style and organizational needs.",
  },

  // Other categories (packing boxes, bottles or sippers, pens, key chains, trophies, travel bags) can follow the same structure.
];

export default productData;
