import ImageLinks from "./imageLink";

const productData = [
  // Coasters
  {
    sku: "cst001",
    name: "Birthday Coaster",
    price: 499,
    category: "coaster",
    imageUrl: ImageLinks.birthday1,
    description: "A beautiful round coaster for your table.",
  },
  {
    sku: "cst002",
    name: "Elegant Printed Coaster",
    price: 299,
    category: "coaster",
    imageUrl: ImageLinks.coasterPrint1,
    description: "Stylish square coaster for drinks.",
  },
  {
    sku: "cst003",
    name: "Designer Coaster",
    price: 399,
    category: "coaster",
    imageUrl: ImageLinks.designerCoaster1,
    description: "Elegant wooden coaster for your table.",
  },
  {
    sku: "cst004",
    name: "Simple Rich Coaster",
    price: 189,
    category: "coaster",
    imageUrl: ImageLinks.normalCoaster1,
    description: "Personalized coaster with custom prints.",
  },
  {
    sku: "cst004",
    name: "Customize Printed Coaster ",
    price: 189,
    category: "coaster",
    imageUrl: ImageLinks.printCoaster1,
    description: "Personalized coaster with custom prints.",
  },
  {
    sku: "cst004",
    name: "Elegant Wooden Coaster",
    price: 189,
    category: "coaster",
    imageUrl: ImageLinks.woodenCoaster1,
    description: "Personalized coaster with custom prints.",
  },
  {
    sku: "cst004",
    name: "Elegant Yellow Shade Coaster",
    price: 189,
    category: "coaster",
    imageUrl: ImageLinks.yellowCoaster1,
    description: "Personalized coaster with custom prints.",
  },

  // Mugs
  {
    sku: "cup001",
    name: "Elegant Chariot Mug",
    price: 19,
    category: "cup",
    imageUrl: ImageLinks.chariot,
    description: "High-quality graphic T-shirt.",
  },
  {
    sku: "cup002",
    name: "Elegant Couch Mug",
    price: 19,
    category: "cup",
    imageUrl: ImageLinks.couch,
    description: "Comfortable plain white T-shirt.",
  },
  {
    sku: "cup003",
    name: "Eye Look Coaster",
    price: 19,
    category: "cup",
    imageUrl: ImageLinks.eye,
    description: "Classic V-neck T-shirt.",
  },
  {
    sku: "cup004",
    name: "Elegant Last Staw Mug",
    price: 29,
    category: "cup",
    imageUrl: ImageLinks.lastStraw,
    description: "T-shirt with personalized designs.",
  },
  {
    sku: "cup005",
    name: "Elegant Lover Mug",
    price: 29,
    category: "cup",
    imageUrl: ImageLinks.lover,
    description: "T-shirt with personalized designs.",
  },
  {
    sku: "cup006",
    name: "Elegant Customize Mom Mug",
    price: 29,
    category: "cup",
    imageUrl: ImageLinks.mom,
    description: "T-shirt with personalized designs.",
  },
  {
    sku: "cup007",
    name: "Elegant Plain Mug",
    price: 29,
    category: "cup",
    imageUrl: ImageLinks.plain,
    description: "T-shirt with personalized designs.",
  },
  {
    sku: "cup008",
    name: "Elegant Prick Mug",
    price: 29,
    category: "cup",
    imageUrl: ImageLinks.pricks,
    description: "T-shirt with personalized designs.",
  },
  {
    sku: "cup0010",
    name: "Elegant Relaxed Mug",
    price: 29,
    category: "cup",
    imageUrl: ImageLinks.relaxation,
    description: "T-shirt with personalized designs.",
  },
  {
    sku: "cup0011",
    name: "Elegant Show Mug",
    price: 29,
    category: "cup",
    imageUrl: ImageLinks.show,
    description: "T-shirt with personalized designs.",
  },
  {
    sku: "cup0012",
    name: "Elegant Star Mug",
    price: 29,
    category: "cup",
    imageUrl: ImageLinks.star,
    description: "T-shirt with personalized designs.",
  },
  {
    sku: "cup0013",
    name: "Customize Star Mug",
    price: 29,
    category: "cup",
    imageUrl: ImageLinks.starMug,
    description: "T-shirt with personalized designs.",
  },
  {
    sku: "cup0014",
    name: "Elegant Strength Mug",
    price: 29,
    category: "cup",
    imageUrl: ImageLinks.strength,
    description: "T-shirt with personalized designs.",
  },
  {
    sku: "cup0015",
    name: "Elegant Symbol Mug",
    price: 29,
    category: "cup",
    imageUrl: ImageLinks.symbol,
    description: "T-shirt with personalized designs.",
  },
  {
    sku: "cup0016",
    name: "Elegant Tarrot Mug",
    price: 29,
    category: "cup",
    imageUrl: ImageLinks.tarrot1,
    description: "T-shirt with personalized designs.",
  },
  {
    sku: "cup0017",
    name: "Elegant Customize Tarrot Mug",
    price: 29,
    category: "cup",
    imageUrl: ImageLinks.tarrot2,
    description: "T-shirt with personalized designs.",
  },
  {
    sku: "cup0018",
    name: "Elegant Designed Tarrot Mug",
    price: 29,
    category: "cup",
    imageUrl: ImageLinks.tarrot3,
    description: "T-shirt with personalized designs.",
  },
  {
    sku: "cup0019",
    name: "Elegant Tarrot Printed Mug",
    price: 29,
    category: "cup",
    imageUrl: ImageLinks.tarrot4,
    description: "T-shirt with personalized designs.",
  },
  {
    sku: "cup0020",
    name: "Elegant Tarrot Customize Mug",
    price: 29,
    category: "cup",
    imageUrl: ImageLinks.tarrot5,
    description: "T-shirt with personalized designs.",
  },
  {
    sku: "cup0019",
    name: "Elegant Customize Yoga Mug",
    price: 29,
    category: "cup",
    imageUrl: ImageLinks.yoga,
    description: "T-shirt with personalized designs.",
  },


  // Sipper
  {
    sku: "sipper001",
    name: "Customize Black Sipper",
    price: 9,
    category: "sipper",
    imageUrl: ImageLinks.blackSipper,
    description: "A sturdy coffee mug for everyday use.",
  },
  {
    sku: "sipper002",
    name: "Elegant Round Black Sipper",
    price: 9,
    category: "sipper",
    imageUrl: ImageLinks.blackSipper2,
    description: "A sturdy coffee mug for everyday use.",
  },
  {
    sku: "sipper003",
    name: "Elegant Black Sipper",
    price: 9,
    category: "sipper",
    imageUrl: ImageLinks.sipperBlack,
    description: "A sturdy coffee mug for everyday use.",
  },
  {
    sku: "sipper004",
    name: "Customize Blue Sipper",
    price: 9,
    category: "sipper",
    imageUrl: ImageLinks.sipperBlue,
    description: "A sturdy coffee mug for everyday use.",
  },
  {
    sku: "sipper005",
    name: "Customize Red Sipper",
    price: 9,
    category: "sipper",
    imageUrl: ImageLinks.sipperRed,
    description: "A sturdy coffee mug for everyday use.",
  },
  {
    sku: "sipper006",
    name: "Customize Silver Sipper",
    price: 9,
    category: "sipper",
    imageUrl: ImageLinks.sipperSilver,
    description: "A sturdy coffee mug for everyday use.",
  },
  {
    sku: "sipper007",
    name: "Customize White Sipper",
    price: 9,
    category: "sipper",
    imageUrl: ImageLinks.sipperWhite,
    description: "A sturdy coffee mug for everyday use.",
  },

  // Tshirts

  {
    sku: "tshirt001",
    name: "Customize White Tshirt",
    price: 9,
    category: "tshirt",
    imageUrl: ImageLinks.white,
    description: "A sturdy coffee mug for everyday use.",
  },
  {
    sku: "tshirt002",
    name: "Customize Dark Green Tshirt",
    price: 9,
    category: "tshirt",
    imageUrl: ImageLinks.darkGreen,
    description: "A sturdy coffee mug for everyday use.",
  },
  {
    sku: "tshirt003",
    name: "Customize Green Tshirt",
    price: 9,
    category: "tshirt",
    imageUrl: ImageLinks.green,
    description: "A sturdy coffee mug for everyday use.",
  },
  {
    sku: "tshirt004",
    name: "Customize Lavender Tshirt",
    price: 9,
    category: "tshirt",
    imageUrl: ImageLinks.lavender,
    description: "A sturdy coffee mug for everyday use.",
  },
  {
    sku: "tshirt005",
    name: "Customize Light Green Tshirt",
    price: 9,
    category: "tshirt",
    imageUrl: ImageLinks.lightGreen,
    description: "A sturdy coffee mug for everyday use.",
  },
  {
    sku: "tshirt006",
    name: "Customize Mint Tshirt",
    price: 9,
    category: "tshirt",
    imageUrl: ImageLinks.mintGreen,
    description: "A sturdy coffee mug for everyday use.",
  },
  {
    sku: "tshirt007",
    name: "Customize Sky Blue Tshirt",
    price: 9,
    category: "tshirt",
    imageUrl: ImageLinks.skyBlue,
    description: "A sturdy coffee mug for everyday use.",
  },


  // Photo Frames
  {
    sku: "pf001",
    name: "Wooden Photo Frame",
    price: 29,
    category: "photo frames",
    imageUrl: ImageLinks.cafe,
    description: "Elegant wooden frame for your memories.",
  },
  {
    sku: "pf002",
    name: "Glass Photo Frame",
    price: 29,
    category: "photo frames",
    imageUrl: ImageLinks.cafe,
    description: "Sleek glass frame for your photos.",
  },
  {
    sku: "pf003",
    name: "Collage Photo Frame",
    price: 39,
    category: "photo frames",
    imageUrl: ImageLinks.cafe,
    description: "Collage frame for multiple photos.",
  },
  {
    sku: "pf004",
    name: "Metallic Photo Frame",
    price: 39,
    category: "photo frames",
    imageUrl: ImageLinks.cafe,
    description: "Durable metallic photo frame.",
  },

  // Diaries or Planners
  {
    sku: "dpl001",
    name: "Leather Planner",
    price: 19,
    category: "diaries or planner",
    imageUrl: ImageLinks.cafe,
    description: "Stylish leather planner for daily notes.",
  },
  {
    sku: "dpl002",
    name: "Hardcover Diary",
    price: 19,
    category: "diaries or planner",
    imageUrl: ImageLinks.cafe,
    description: "Durable hardcover diary for journaling.",
  },
  {
    sku: "dpl003",
    name: "Pocket Planner",
    price: 19,
    category: "diaries or planner",
    imageUrl: ImageLinks.cafe,
    description: "Compact planner to carry everywhere.",
  },
  {
    sku: "dpl004",
    name: "Custom Planner",
    price: 29,
    category: "diaries or planner",
    imageUrl: ImageLinks.cafe,
    description: "Personalized planner with your design.",
  },

  // Organizers
  {
    sku: "org001",
    name: "Desk Organizer",
    price: 19,
    category: "organiser",
    imageUrl: ImageLinks.cafe,
    description: "Keep your desk clean and organized.",
  },
  {
    sku: "org002",
    name: "Drawer Organizer",
    price: 19,
    category: "organiser",
    imageUrl: ImageLinks.cafe,
    description: "Perfect for organizing drawers.",
  },
  {
    sku: "org003",
    name: "Travel Organizer",
    price: 19,
    category: "organiser",
    imageUrl: ImageLinks.cafe,
    description: "Compact organizer for travel essentials.",
  },
  {
    sku: "org004",
    name: "Custom Organizer",
    price: 29,
    category: "organiser",
    imageUrl: ImageLinks.cafe,
    description: "Personalized organizer for your needs.",
  },

  // Other categories (packing boxes, bottles or sippers, pens, key chains, trophies, travel bags) can follow the same structure.
];

export default productData;
